### ISSUE TITLE
Builder Profunctor instance

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-record#32]
There should be a `Profunctor` instance for `Builder`s.

**Comment by hdgarrood** [comment]
I'm not sure this is doable, actually. The problem is that, as I understand it, a `Builder a b` is a function `a -> b` which is guaranteed to use its argument exactly once, but allowing you to `lmap` with any old function could break that guarantee. I've haven't been able to come up with an example of this breaking things yet but I expect it can be done.

@paf31 does this sound reasonable?

**Comment by matthewleon** [comment]
@hdgarrood I see what you're saying.

**Comment by paf31** [comment]
Something like `lmap (const r) builder` seems like it would cause trouble by modifying the immutable record `r`.
